#pragma once

blas_status sgemm_nn(int m, int n, int k, const float *alpha, const float *A, int lda, const float *B, int ldb, const float *beta, float *C, int ldc);

void sgemm_strided_batched_nn(int m,
	int n,
	int k,
	const float* alpha_p,
	const float* A,
	int lda,
	int stride_a,
	const float* B,
	int ldb,
	int stride_b,
	const float* beta_p,
	float* C,
	int ldc,
	int stride_c,
	int batch_count);

void sgemm_strided_batched_nt(int m,
	int n,
	int k,
	const float* alpha_p,
	const float* A,
	int lda,
	int stride_a,
	const float* B,
	int ldb,
	int stride_b,
	const float* beta_p,
	float* C,
	int ldc,
	int stride_c,
	int batch_count);

void sgemm_strided_batched_tn(int m,
	int n,
	int k,
	const float* alpha_p,
	const float* A,
	int lda,
	int stride_a,
	const float* B,
	int ldb,
	int stride_b,
	const float* beta_p,
	float* C,
	int ldc,
	int stride_c,
	int batch_count);
void sgemm_strided_batched_tt(int m,
	int n,
	int k,
	const float* alpha_p,
	const float* A,
	int lda,
	int stride_a,
	const float* B,
	int ldb,
	int stride_b,
	const float* beta_p,
	float* C,
	int ldc,
	int stride_c,
	int batch_count);
